dist: trusty
sudo: required
language: generic

branches:
  only:
  - master

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="CoqEAL"
  matrix:
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.7"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.8"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.9"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.10"
  - DOCKERIMAGE="mathcomp/mathcomp:1.11.0-coq-8.11"

install:
- docker pull ${DOCKERIMAGE}
- docker tag  ${DOCKERIMAGE} ci:current
- docker run  --env=OPAMYES --init -id --name=CI -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB} -w /home/coq/${CONTRIB} ci:current
- docker exec CI /bin/bash --login -c "cd ..; curl -LO https://github.com/math-comp/finmap/archive/1.5.0.tar.gz; tar -xvzf 1.5.0.tar.gz; cd finmap-1.5.0/; opam pin add -y -n coq-mathcomp-finmap.1.5.0 .; opam install coq-mathcomp-finmap.1.5.0; cd /home/coq/${CONTRIB}" # remove when finmap 1.5.0 is released
- docker exec CI /bin/bash --login -c "cd ..; curl -LO https://github.com/math-comp/multinomials/archive/f2db7f388d81b46877af4c085855a5e1245ae777.tar.gz; tar -xvzf f2db7f388d81b46877af4c085855a5e1245ae777.tar.gz; cd multinomials-*/; opam pin add -y -n coq-mathcomp-multinomials.1.6 .; opam install coq-mathcomp-multinomials.1.6; cd /home/coq/${CONTRIB}" # remove when multinomials 1.6 is released
- docker exec CI /bin/bash --login -c "opam pin add -n coq-mathcomp-${CONTRIB} ."
- docker exec CI /bin/bash --login -c "opam install --deps-only coq-mathcomp-${CONTRIB}"

script:
- docker exec CI /bin/bash --login -c "opam install ."
